name: minhdattrinh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # Added dependencies for API, Storage and Date Formatting
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  table_calendar: ^3.1.3
  flutter_vector_icons: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^6.0.0

  # Dependencies for Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
